### ISSUE TITLE
about merge_lidar.py

### ISSUE THREAD

**Issue by Mr-ind1fferent** [lifuguan/XLD_code#5]
Thanks for the amazing work!

The script merge_lidar.py can not  generate merge_cloud.txt, only merge_cloud.ply

**Comment by HengDora** [comment]
Hello!

I have the same problem as you, after conversion I get all ply point clouds and no point clouds in txt format. I observe that you have closed the problem, is it convenient to ask how you solved it?

Thank you very much!

**Comment by Mr-ind1fferent** [comment]
I just use colmap to solve the problem
